### ISSUE TITLE
t after show date 

### ISSUE THREAD

**Issue by PeterZ99** [schreibfaul1/ESP8266-LED-Matrix-Clock#2]
https://github.com/schreibfaul1/ESP8266-LED-Matrix-Clock/blob/443776cca2d181c8234279b505ea9a539671d5e8/MatrixClock.ino#L857

change to 

char2Arr(M_arr[MEZ.mon12 - 1][4], d_PosX - 55, 0);

**Comment by schreibfaul1** [comment]
Yes, thanks!
