### ISSUE TITLE
Date display

### ISSUE THREAD

**Issue by zangaby** [schreibfaul1/ESP8266-LED-Matrix-Clock#3]
Hi,

Thank you for this great project !

I ordered the parts and assembled everything but I noticed one small issue on the date display, today it's displaying ' Tu,19DezV2017', any idea from where that 'V' might be coming from?

**Comment by schreibfaul1** [comment]
Hello,
look at the arrays at line 71...79, every month has 5, every day 3 characters, If You have translated the names it can be that one array has now more of less chars as normal

**Comment by zangaby** [comment]
Hi,
Thank you for your reply !
I have indeed translated the names, but I made sure I left the same number of characters.

**Comment by schreibfaul1** [comment]
please try this, it works for me
//months
char M_arr[12][5] = { { '.', 'J', 'a', 'n', '.' }, { '.', 'F', 'e', 'b', '.' },
		{ '.', 'M', 'a', 'r', '.' }, { '.', 'A', 'p', 'r', '.' }, { '.', 'M', 'a',
				'y', ' ' }, { '.', 'J', 'u', 'n', 'e' }, { '.', 'J', 'u', 'l', 'y' }, {
				'.', 'A', 'u', 'g', '.' }, { '.', 'S', 'e', 'p', 't' }, { '.', 'O', 'c',
				't', '.' }, { '.', 'N', 'o', 'v', '.' }, { '.', 'D', 'e', 'c', '.' } };
//days
char WT_arr[7][3] = { { 'S', 'o', ',' }, { 'M', 'o', ',' }, { 'T', 'u', ',' }, {
		'W', 'e', ',' }, { 'T', 'h', ',' }, { 'F', 'r', ',' }, { 'S', 'a', ',' } };

**Comment by zangaby** [comment]
Thank you , just tried it now and unfortunately it's doing the same.
Not sure what I might be doing wrong.

**Comment by zangaby** [comment]
Re-downloaded the code, re-flashed the nodemcu and now it's all good.
Thanks again !
