### ISSUE TITLE
Thanks for sharing the project. My clock is not showing the right time but is showing the right date. How to change the time zone? I live in Bangalore, India.

### ISSUE THREAD

**Issue by Aksin7** [schreibfaul1/ESP8266-LED-Matrix-Clock#4]

**Comment by schreibfaul1** [comment]
Bangalort time is GMT+5:30
Line 241 change:     t = epoch+5.5*3600;
Is there no daylightsavingtime You can comment line 401 ... 477

**Comment by Aksin7** [comment]
schreibfaul1 thanks a Ton. It worked as you said. I am a noob. Can you please help me with one more thing. Can you tell how to get this in 12 hour clock format.

**Comment by schreibfaul1** [comment]
Hello Asksin7
see my new project with ESP32 in my github, all timezones around the world can be set,
external RTC is no longer needed,
time format can be 24h or 12h

**Comment by Aksin7** [comment]
Hi Schreibfaul1,
          Thank you for the code. Can you please help in the esp8266 code for 12 hour format.
