### ISSUE TITLE
Thanks for the beautiful project - about the Brazilian timezone

### ISSUE THREAD

**Issue by Dancopy** [schreibfaul1/ESP8266-LED-Matrix-Clock#5]
Greetings schreibfaul1!
How would you look in the code for the Brazilian time zone + daylight saving time?
In my region, the Time zone of Brazil is -3 and the Brazilian Summer Time 2018-2019: 04 November 2018 until 17 February 2019. Thank you very much

**Comment by schreibfaul1** [comment]
Hello Dancopy,
this project is made for middle europe.  It is difficult to include every timezones and specific summer/wintertime. I will make a new project with ESP32. ESP32 has a internally RTC. Then it is easy to set every time (daylight saving time, 12/24h am/pm format etc.) around the world. 
As workaround uncomment line 245 and set the timedifference 
epoch=epoch+3600*3;
means plus 3 hours

**Comment by Dancopy** [comment]
Line 245 is this: if (cb == 48)   (Comment this line?)
And line 242 is: t = epoch;       (Do so?) epoch = epoch +3600*3;
Thank you+

**Comment by Dancopy** [comment]
Sorry, this line is already Uncommented!

**Comment by Dancopy** [comment]
Ok friend, I'll test; thanks again

**Comment by schreibfaul1** [comment]
see my new project on github ESP32 MartixClock, You can set the timezones around the world
