### ISSUE TITLE
geht 1 sek nach?

### ISSUE THREAD

**Issue by Robiv8** [schreibfaul1/ESP8266-LED-Matrix-Clock#6]
Hallo,
Diese Uhr ist klasse und läuft einwandfrei.
Jedoch geht sie ca 1 sek nach? Sprich wenn ich diese vergleiche mit anderen Uhren dann hinkt diese um 1 sek nach.
Kann man das irgendwo einstellen? Um 1 Sek vorstellen oder ähnlich.
Danke

**Comment by schreibfaul1** [comment]
Hallo Robiv8
in Zeile 244 kann die Zeitdifferenz verändert werden
`
epoch = secsSince1900 - seventyYears +2; //+2000ms Verarbeitungszeit
`
die zwei Sekunden habe ich willkürlich gesetzt, mangels einer genauen Zeitrefernz.
Setzte
`
epoch = secsSince1900 - seventyYears +1;
` 
um die Zeit zu korrigieren.

**Comment by Robiv8** [comment]
Super Danke
