### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by mib1978** [schreibfaul1/ESP8266-LED-Matrix-Clock#8]
Hello! I realize your project, but I have a problem with displays. My Matrix array show the character set in vertical position, not horizontaly. Is some possibility to rotate the display with 90 degrees to correct that? Thank you!

![Clipboard01](https://user-images.githubusercontent.com/10261776/54602175-9edf1980-4a49-11e9-9923-7de4415f82c3.jpg)

**Comment by schreibfaul1** [comment]
Hello, I have added some items to flip the orientation, so uncomment one or more and see what happens, maybe it works 
````c++
// other displays -------------------------------------
//#define REVERSE_HORIZONTAL                        // Parola, Generic and IC-Station
//#define REVERSE_VERTICAL                          // IC-Station display
//#define ROTATE_90                                 // Generic display
````

**Comment by mib1978** [comment]
Hello!Thanks a lot for your help. Now everything is almost correct. For my display I use REVERSE_HORIZONTAL and ROTATE_90 (with ROTATE_90 only,  the display show correct position, but mirrored). After that is ok, but appear some artefacts on scrolling data (I put one picture in attachement). All the best and thanks again.
    Pe miercuri, 27 martie 2019, 09:46:20 EET, Wolle <notifications@github.com> a scris:  
 
 
Hello, I have added some items to flip the orientation, so uncomment one or more and see what happens, maybe it works
// other displays -------------------------------------
//#define REVERSE_HORIZONTAL                        // Parola, Generic and IC-Station
//#define REVERSE_VERTICAL                          // IC-Station display
//#define ROTATE_90                                 // Generic display
