### ISSUE TITLE
Please Help me with Your project.

### ISSUE THREAD

**Issue by Robarco** [schreibfaul1/ESP8266-LED-Matrix-Clock#9]
12:48:48.341 -> sending NTP packet...
12:48:49.326 -> no timepacket received
12:48:49.326 -> decrease brightness
And RTC setup to date anyway the clock shows time 0:00:00 and sate 1.01.2000

**Comment by Robarco** [comment]
But in com scan date is correct

**Comment by schreibfaul1** [comment]
Is port 123 open, check the firewall

**Comment by Robarco** [comment]
Excuse me???



Wysłano z mojego smartfona Samsung Galaxy.


-------- Oryginalna wiadomość --------
Od: Wolle <notifications@github.com>
Data: 01.05.2019 15:51 (GMT+00:00)
Do: schreibfaul1/ESP8266-LED-Matrix-Clock <ESP8266-LED-Matrix-Clock@noreply.github.com>
DW: Robarco <robarco.electric@hotmail.com>, Author <author@noreply.github.com>
Temat: Re: [schreibfaul1/ESP8266-LED-Matrix-Clock] Please Help me with Your project. (#9)


Is port 123 open, check the firewall
